/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 envelope.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
    github: THREE.Mesh
    resume: THREE.Mesh
    linkedin: THREE.Mesh
    Envelope001: THREE.Mesh
    Envelope002: THREE.Mesh
  }
  materials: {
    inner: THREE.MeshStandardMaterial
    outer: THREE.MeshStandardMaterial
    card: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/envelope.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.003, 0.707, 0]}>
        <mesh geometry={nodes.Plane001.geometry} material={materials.inner} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials.outer} />
      </group>
      <mesh geometry={nodes.github.geometry} material={materials.card} />
      <mesh geometry={nodes.resume.geometry} material={materials.card} />
      <mesh geometry={nodes.linkedin.geometry} material={materials.card} />
      <mesh geometry={nodes.Envelope001.geometry} material={materials.outer} />
      <mesh geometry={nodes.Envelope002.geometry} material={materials.outer} position={[0.01, 0, 0]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.inner} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials.outer} />
      <mesh geometry={nodes.Plane003.geometry} material={materials.card} />
      <mesh geometry={nodes.Plane003_1.geometry} material={materials.outer} />
    </group>
  )
}

useGLTF.preload('/envelope.glb')
