/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 envelope.glb -t 
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
    github: THREE.Mesh
    resume: THREE.Mesh
    linkedin: THREE.Mesh
  }
  materials: {
    inner: THREE.MeshPhysicalMaterial 
    outer: THREE.MeshPhysicalMaterial 
    card: THREE.MeshPhysicalMaterial 
  }
}

export function Envelope(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Portfolio2025/envelope.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null} scale={2.5} rotation={[Math.PI/2, -Math.PI/2, Math.PI/2 ]} position={[0, -1, 0]}>
      {/* Flap */}
      <group position={[-0.003, 0.707, 0.01]} rotation={[0, 0, Math.PI/1]}>
        <mesh geometry={nodes.Plane001.geometry} material={materials.inner} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials.outer} />
      </group>

      {/* Card */}
      <group position={[0, -0.8, 0]} >
        <mesh geometry={nodes.github.geometry} material={materials.card} />
        <mesh geometry={nodes.resume.geometry} material={materials.card} />
        <mesh geometry={nodes.linkedin.geometry} material={materials.card} />
        <mesh geometry={nodes.Plane003.geometry} material={materials.card} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials.outer} />        
      </group>

      {/* Envelope body */}
      <mesh geometry={nodes.Plane.geometry} material={materials.inner} />
      <mesh geometry={nodes.Plane_1.geometry} material={materials.outer} />
    </group>
  )
}

useGLTF.preload('/Portfolio2025/envelope.glb')
