/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 folder.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import { useEffect, useRef, useState, type JSX } from 'react'
import type { ThreeEvent } from '@react-three/fiber'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap';

type GLTFResult = GLTF & {
  nodes: {
    back: THREE.Mesh
    front: THREE.Mesh
    mainPaper: THREE.Mesh
    blueFramed: THREE.Mesh
    newspaper: THREE.Mesh
  }
  materials: {
    folder: THREE.MeshStandardMaterial
    mainPaper: THREE.MeshStandardMaterial
    blueFramed: THREE.MeshStandardMaterial
    newspaper: THREE.MeshStandardMaterial
  }
}

export function FolderModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Portfolio2025/folder.glb') as unknown as GLTFResult

  let isSmallScreen = window.innerWidth > 1280 ? false : true;

  const groupRef = useRef<THREE.Group>(null);
  const frontRef = useRef<THREE.Mesh>(null);

  const { contextSafe } = useGSAP({ scope: groupRef });

  const [frontOpen, setFrontOpen] = useState(false);

  useEffect(() => {
    const texture = new THREE.TextureLoader().load('/Portfolio2025/assets/folderPaper.jpg');
    texture.flipY = false;
    texture.anisotropy = 0;
    texture.magFilter = THREE.NearestFilter;
    texture.minFilter = THREE.NearestFilter;
    texture.colorSpace = THREE.SRGBColorSpace;
    materials.folder.map = texture;

    const texture2 = new THREE.TextureLoader().load('/Portfolio2025/assets/homeNote.png');
    texture2.flipY = false;
    texture2.anisotropy = 0;
    texture2.magFilter = THREE.NearestFilter;
    texture2.minFilter = THREE.NearestFilter;
    texture2.colorSpace = THREE.SRGBColorSpace;
    materials.mainPaper.map = texture2;
  }, [])

  const onFrontClick = contextSafe((e:ThreeEvent<MouseEvent>) => {
    e.stopPropagation();

    console.log('clicked front');

    if (frontRef.current) {
      if (frontOpen) {
        gsap.to(frontRef.current.rotation, { x: 0, duration: 0.8, ease: "power2.out" }).then(() => {
          setFrontOpen(false);
        });

      } else {
        gsap.to(frontRef.current.rotation, { x: Math.PI/2 + 1, duration: 0.6, ease: "power2.out" })
        setFrontOpen(true);
      }
    }
  })

  const onHover = contextSafe((e: ThreeEvent<MouseEvent>, entering: boolean) => {
    e.stopPropagation();

    if (frontRef.current) {
      if (entering && !frontOpen) {
        gsap.to(frontRef.current.rotation, { x: 0.05, y: 0, z: 0, duration: 0.2 });
      } else if (!entering && !frontOpen) {
        gsap.to(frontRef.current.rotation, { x: 0, y: 0, z: 0, duration: 0.2 });
      }
    }
  })

  return (
    <group {...props} dispose={null} rotation={[Math.PI/2, 0, 0]} scale={isSmallScreen ? 0.3 : 0.5} ref={groupRef} onPointerEnter={(e) => onHover(e, true)} onPointerLeave={(e) => onHover(e, false)}>
      <mesh geometry={nodes.back.geometry} material={materials.folder} scale={[1.239, 1, 0.807]} />
      <mesh geometry={nodes.front.geometry} material={materials.folder} position={[0.124, 0.207, 4.18]} ref={frontRef} onClick={(e) => onFrontClick(e)} />
      <mesh geometry={nodes.mainPaper.geometry} material={materials.mainPaper} position={[0.124, 0.144, 0.082]} scale={[-5.084, -2.142, -3.585]} rotation={[0, 0, 0]}/>
      <mesh geometry={nodes.blueFramed.geometry} material={materials.blueFramed} position={[-1.101, 0.046, -1.337]} rotation={[0, 0.053, 0]} scale={[3.68, 2.629, 2.85]} />
      <mesh geometry={nodes.newspaper.geometry} material={materials.newspaper} position={[0.505, 0.065, -0.785]} scale={[4.909, 1.341, 3.179]} />
    </group>
  )
}

useGLTF.preload('/Portfolio2025/folder.glb')
